version: '3.9'
services:
  postgres:
    container_name: postDb
    image: postgres:latest
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=goBank
    ports:
      - "5432:5432"
    networks:
      - backend
  api:
    container_name: app
    image: gobank:latest
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/goBank?sslmode=disable
    networks:
      - backend
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]

networks:
  backend: