apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::735542962543:user/github.ci
      username: github.ci
      groups:
        - system:masters